# 1. Create a 3x3x3 array with random values 

In [37]:
import numpy as np 
        
# Creating 3D array with random values
array = np.random.random((3, 3 ,3)) 

# Creating 3D array with random values
array1 = np.random.rand(3, 3 ,3) 

print("3D Array with random values (technique 1): \n", array); 

print("\n3D Array with random values (technique 2): \n", array1);


3D Array with random values (technique 1): 
 [[[0.47581604 0.99978011 0.17276289]
  [0.45499192 0.02072307 0.63657224]
  [0.69178466 0.63477842 0.13620931]]

 [[0.51354728 0.31773488 0.98763912]
  [0.76981744 0.28527201 0.59810539]
  [0.43121478 0.37140564 0.61099529]]

 [[0.83269521 0.3834257  0.31111429]
  [0.29451035 0.68238534 0.48902571]
  [0.24261698 0.93032464 0.60526717]]]

3D Array with random values (technique 2): 
 [[[0.8589098  0.53642163 0.58539597]
  [0.33366134 0.79287566 0.54136385]
  [0.80895094 0.88963115 0.84040068]]

 [[0.45454712 0.50418526 0.58196645]
  [0.02513209 0.14787456 0.34993682]
  [0.63722532 0.43288423 0.34806534]]

 [[0.9793383  0.82775811 0.54539218]
  [0.46819197 0.58071015 0.96533636]
  [0.20975115 0.33477903 0.37183815]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
import numpy as np

ArrayList = [1,2,3,4,5]

x = np.zeros((5,5))
x += ArrayList
x = np.tril(x, 0)

print("Matrix with values 1,2,3,4 just below the diagonal")  
print(x)

Matrix with values 1,2,3,4 just below the diagonal
[[1. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [1. 2. 3. 0. 0.]
 [1. 2. 3. 4. 0.]
 [1. 2. 3. 4. 5.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
import numpy as np

# Create a 8x8 array with all zeros and datatype as 'int'
x = np.zeros((8,8),dtype=int)

# Make elements equal to '1' from every second row(starting from 1st row) and 
# every second column(starting from 0th column)
x[1::2,::2] = 1

# Make elements equal to '1' from every second row(starting from 0th row) and 
# every second column(starting from 1st column)
x[::2,1::2] = 1

# Printing checkerboard pattern
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [48]:
import numpy as np
from numpy import linalg as lalg

# Function that normalizes each row of the matrix x to have unit length.
def normalize_rows(x):
    return x/lalg.norm(x, ord=2, axis=1, keepdims=True)

# Creating 5x5 array with random values
array = np.random.rand(5, 5)

print("5x5 Array with random values: \n", array, "\n");

narray = normalize_rows(array)

print("Atfter normalization: \n", narray, "\n")

5x5 Array with random values: 
 [[0.87751337 0.67371382 0.27517769 0.18255748 0.45471763]
 [0.51330202 0.29543531 0.98367032 0.40118599 0.28902066]
 [0.15702315 0.14830878 0.25698778 0.25057751 0.05147401]
 [0.98236556 0.53203341 0.76630968 0.36232391 0.85176098]
 [0.20313221 0.51766408 0.31072978 0.64714298 0.03146664]] 

Atfter normalization: 
 [[0.70718055 0.54294023 0.22176336 0.14712152 0.36645307]
 [0.41059544 0.23632168 0.78684778 0.3209127  0.23119053]
 [0.37204144 0.35139413 0.60889177 0.59370365 0.12195949]
 [0.59872435 0.32425949 0.46704434 0.2208263  0.51912452]
 [0.22356318 0.56973055 0.34198287 0.71223239 0.03463154]] 



# 5.  How to find common values between two arrays?

In [56]:
import numpy as np

array1 = [0, 100, 200, 400, 700]
print("Array1: ", array1, "\n")
array2 = [100, 300, 400, 700]
print("Array2: ", array2, "\n")

# Get common values between two arrays with indices
CommonValues, array1_idx, array2_idx = np.intersect1d(array1, array2, return_indices=True) 

print("Common values between two arrays:", CommonValues, "\n")

print("Index of common values at Array1:", array1_idx, "\n")

print("Index of common values at Array2:", array2_idx, "\n")

Array1:  [0, 100, 200, 400, 700] 

Array2:  [100, 300, 400, 700] 

Common values between two arrays: [100 400 700] 

Index of common values at Array1: [1 3 4] 

Index of common values at Array2: [0 2 3] 



# 6.How to get the dates of yesterday, today and tomorrow?

In [57]:
import numpy as np

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's date: ",yesterday)

today     = np.datetime64('today', 'D')
print("Today's date: ",today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date: ",tomorrow)

Yestraday's date:  2020-07-25
Today's date:  2020-07-26
Tomorrow's date:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [68]:
import numpy as np

# Create random array with 10 elements between 0 and 10 
array1 = np.random.randint(0,10,10)
print("First array:", array1)

# Create random array with 10 elements between 0 and 10
array2 = np.random.randint(0,10,10)
print("Second array:", array2)

# Checking whether the above two array are equal or not
IsEqual = np.allclose(array1, array2)
print("Above two arrays are equal or not:", IsEqual)

First array: [9 5 0 0 2 8 3 2 8 9]
Second array: [5 6 8 6 5 0 1 3 5 3]
Above two arrays are equal or not: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [78]:
import numpy as np

# Create random array of size 10
x = np.random.random(10)
print("Random vector:\n", x)
print("Vector size:", x.size, "\n")

idx = x.argmax()
print("Maximum value at:", idx, "\n")
x[idx] = 0
print("Maximum value replaced by 0:\n", x)

Random vector:
 [0.49440972 0.23246454 0.05642534 0.25290347 0.43506636 0.06520623
 0.47794832 0.73346153 0.1851558  0.95703345]
Vector size: 10 

Maximum value at: 9 

Maximum value replaced by 0:
 [0.49440972 0.23246454 0.05642534 0.25290347 0.43506636 0.06520623
 0.47794832 0.73346153 0.1851558  0.        ]


# 9. How to print all the values of an array?

In [86]:
import numpy as np

# Create random array of size 10
x = np.random.random(10)
print("Random vector:\n", x)
print("Vector size:", x.size, "\n")

for i in range(x.size):
    print(x[i], "\n")


Random vector:
 [0.58051384 0.07676684 0.60081984 ... 0.78037802 0.78256999 0.66587198]
Vector size: 10 

0.5805138389420227 

0.07676683687087593 

0.6008198381057386 

0.620636998099783 

0.09988666763018794 

0.38830775100128456 

0.7042293757506937 

0.7803780203152204 

0.782569988896746 

0.6658719798251708 



# 10.Subtract the mean of each row of a matrix

In [95]:
import numpy as np

array = np.random.rand(5, 5)
print("Original matrix:\n", array, "\n")

print("Mean of each row:", "\n", array.mean(axis=1, keepdims=True))

Y = array - array.mean(axis=1, keepdims=True)
print("\nSubtract the mean of each row of the said matrix:\n", Y)

Original matrix:
 [[0.10336665 0.1847203  0.43804461 0.75418131 0.93378631]
 [0.18170926 0.78357586 0.03171687 0.59306123 0.64557754]
 [0.77328079 0.41377365 0.71085774 0.0035048  0.20013562]
 [0.11934359 0.85799429 0.15844152 0.31447858 0.98830633]
 [0.20213586 0.67391725 0.58040324 0.24856433 0.63072157]] 

Mean of each row: 
 [[0.48281984]
 [0.44712815]
 [0.42031052]
 [0.48771286]
 [0.46714845]]

Subtract the mean of each row of the said matrix:
 [[-0.37945319 -0.29809953 -0.04477522  0.27136148  0.45096647]
 [-0.26541889  0.33644771 -0.41541128  0.14593308  0.19844939]
 [ 0.35297027 -0.00653687  0.29054722 -0.41680572 -0.2201749 ]
 [-0.36836927  0.37028143 -0.32927134 -0.17323428  0.50059347]
 [-0.26501259  0.2067688   0.11325479 -0.21858412  0.16357312]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [10]:
import numpy as np

# Generating two vectors
xVector = np.random.randint(100, size=10)
yVector = np.random.randint(10, size=5)   # This vector will be used as index vector

# Removing duplicate values from second vector
y = list(set(yVector))
yVector = np.array(y)

print("Vector:", xVector, "\n")
print("Index vector:", yVector, "\n")

# Adding 1 to each element of a vector indexed by second vector
for i in yVector:
    xVector[i] += 1
    
# Printing result
print("Processed vector:", xVector)

Vector: [63 28 78 54 15 75 24 78 28 92] 

Index vector: [9 5 7] 

Processed vector: [63 28 78 54 15 76 24 79 28 93]


# 12.How to get the diagonal of a dot product?

In [17]:
import numpy as np

a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[4, 1, 0], [2, 2, 0], [0, 0, 0]]
c = np.dot(a, b)

print("Dot product: \n", c, "\n")

print("Diagonal:", c.diagonal())

Dot product: 
 [[ 8  5  0]
 [26 14  0]
 [44 23  0]] 

Diagonal: [ 8 14  0]


# 13.How to find the most frequent value in an array?

In [19]:
import numpy as np

xArray = np.random.randint(50, size=10)
print("Original array:\n", xArray)

y = np.bincount(xArray).argmax()
print("Most frequent value in the above array:", y)

Original array:
 [39  0 16 42 26  9 40 38 27 26]
Most frequent value in the above array: 26


# 14.How to get the n largest values of an array

In [27]:
import numpy as np

xArray = np.random.randint(30, size = 15)
print("Original array:\n", xArray)

np.random.shuffle(xArray)

n = int(input("How many largest values of an array?"))

# Getting 'n' largest values of an array
print(n, "largest values of the array:\n", xArray[np.argsort(xArray)[-n:]])

Original array:
 [ 7  0 22 20 28 29 19 16  3 22  0 11  0 15 26]
How many largest values of an array?5
5 largest values of the array:
 [22 22 26 28 29]


# 15.How to create a record array from a regular array?

In [47]:
import numpy as np

# Regular array
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])

# Record array
result= np.core.records.fromarrays([a1, a2, a3],
        dtype=np.dtype([('a', np.float), ('b','S10'), ('c', np.float)]))

for i in range(result.size):
    print(result[i])

(1., b'Red', 12.2)
(2., b'Green', 15.)
(3., b'White', 20.)
(4., b'Orange', 40.)
